#!/usr/bin/env python2
import dbus
import sys

session_bus = dbus.SessionBus()
try:
    spotify_bus = session_bus.get_object(
        'org.mpris.MediaPlayer2.spotify', '/org/mpris/MediaPlayer2')
except dbus.DBusException:
    print 'Spotify Down'
    sys.exit(0)

if (len(sys.argv) == 2):
    spotify_iface = dbus.Interface(
            spotify_bus, 'org.mpris.MediaPlayer2.Player')
    if sys.argv[1] == 'toggle':
        spotify_iface.PlayPause()
    elif sys.argv[1] == 'play':
        spotify_iface.Play()
    elif sys.argv[1] == 'pause':
        spotify_iface.Pause()
    elif sys.argv[1] == 'stop':
        spotify_iface.Stop()
    elif sys.argv[1] == 'next':
        spotify_iface.Next()
    elif sys.argv[1] == 'prev':
        spotify_iface.Previous()
    elif sys.argv[1] == 'isPlaying':
        spotify_props = dbus.Interface(
            spotify_bus, 'org.freedesktop.DBus.Properties')
        print spotify_props.Get('org.mpris.MediaPlayer2.Player',
            'PlaybackStatus').encode('utf-8')
else:
    spotify_props = dbus.Interface(
        spotify_bus, 'org.freedesktop.DBus.Properties')
    song_info = spotify_props.Get(
        'org.mpris.MediaPlayer2.Player', 'Metadata')
    artist = song_info['xesam:artist'][0].encode('utf-8')
    title = song_info['xesam:title'].encode('utf-8')
    print(artist + " - " + title)
